version: '3.9'

services:
  postgres:
    container_name: database
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

  certificate:
    container_name: openssl
    build:
      context: certs
      dockerfile: .cert.Dockerfile
    volumes:
      - type: bind
        source: ./certs/generated
        target: /certs/generated
        read_only: false
        bind:
          create_host_path: true
    tty: true

volumes:
  db:
